version: '3.8'
networks:
  aeroport:

volumes:
  data:

services:

  db:
    container_name: database
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=@Cloud2023
      - POSTGRES_USER=Moi
      - POSTGRES_DB=aeroport
    ports:
      - '5432:5432'
    networks:
      - aeroport
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    container_name: zaventem
    build: ../Airport
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - aeroport
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aeroport
      - POSTGRES_USERNAME=Moi
      - POSTGRES_PASSWORD=@Cloud2023
      - DATA_INIT=true
      - DDL=validate
